### PR TITLE
Create JavaScript implementation

### LINKED ISSUE #1: JavaScript coder wanted
I want help from someone that codes javascript so I can add the javascript version on to SnapCups

### PR DESCRIPTION
**Pull request by R4356th**
### Resolves

Resolves #1.

### Changes

Adds JavaScript implementation

### Testing

Open your browser's console, copy-paste and run it.

### CODE REVIEW

**Comment by R4356th** [comment]
Remember that the contents of the page will be replaced with the link. I could change this though.

**Comment by Daniel4-Scratch** [comment]
Um, I’ll see how the code is and approve it if I want, there is a already a another one

**Comment by Daniel4-Scratch** [comment]
We have one that you can use via the site so I will not add this to the master

**Comment by R4356th** [comment]
Okay.

**Comment by R4356th** [comment]
@Daniel4-Scratch, why did you merge this?

**Pull request merged**
